// event listener to respond to "Show another quote" button clicks
// when user clicks anywhere on the button, the "printQuote" function is called
document.getElementById('loadQuote').addEventListener("click", printQuote, false);

// Variable to hold our messages generated by the printQuote() function:
var message = '';
// Variable to hold spliced quotes
var getQuote = [];
// Variable to hold the refresh timer
var intervalID;

// Print function used throughout the TreeHouse JavaScript tutorial videos:
function print(message) {
	var div = document.getElementById('quote-box');
	div.innerHTML = message;
}

/* Function to iterate through our quotes and randomly select one base on its index #
 This dosen't select the quote property/value from the quotes Array, but rather the 
 entire object at that Arrays index.*/
function getRandomQuote() {
	var randomQuote = Math.floor(Math.random() * quotes.length);

	var spliceQuote = quotes.splice(randomQuote, 1)[0]; // Removes the 0 index object and puts it into the 0 index position of spliceQuote

	getQuote.push(spliceQuote);

	if ( quotes.length === 0) {
		quotes = getQuote;
		getQuote = [];

	}
	return spliceQuote;	
}


// This function will actually get at the property/values of the objects returned by getRandomQuote()
function printQuote() {
	var myQuotes = getRandomQuote();
	message = '<p class="quote">' + myQuotes.quote  + '</p>';
	message += '<p class="source">' + myQuotes.source;
	message += '<span class="citation">' + myQuotes.citation + '</span>' + '</p>';
        for (var i = 0; i < myQuotes.tags.length; i++) {
        message += '<span class="tag" id="tag">' + myQuotes.tags[i] + '</span>';
    }
    // Log random quote to console to verify that each is unique:
    console.log("The random quote generated is: " + myQuotes.quote); 
	print(message);
	randomizeBackgroundColor();
	// This is the only way I could figure out how to call the fade effect to work
	fadeInterval();
}

// This is pretty much plagerized from the Web, I did however spend about 2 hours trying to get my custom colors
function getRandomColor(){
    var letters = ['c5d5cb','9fa8a3','c9d8c5','a8b6bf','b3c2bf','3b3a36','daad86','7d4627','729f98','283018','aa863a'];
    var color = '#';
    color += letters[Math.floor(Math.random() * letters.length)];
    // Just to see what colors are being chosen:
    console.log(color);
    return color;

}


function randomizeBackgroundColor(){
    document.getElementById('background').style.background = getRandomColor();
}

function quoteRefresh(){
        intervalID = window.setInterval(printQuote, 15000);

}

/* This took me a long time to figure out, and I don't know if it is appropriate to put jQuery in your JavaScript file
but...I was really happy to create a fade effect that worked with the quoteRefresh() function */
function fadeInterval(){
	$('#quote-box').hide();
	$('#quote-box').fadeIn(1000);
}



